# Generated by Django 2.0.1 on 2018-03-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotuto_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='var',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='var',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotuto_models.Device'),
        ),
        migrations.AddField(
            model_name='var',
            name='var_type',
            field=models.CharField(choices=[(1, 'Food'), (2, 'Voltaje'), (3, 'Presion')], default=2, max_length=15),
        ),
        migrations.AddField(
            model_name='network',
            name='devices',
            field=models.ManyToManyField(null=True, to='fotuto_models.Device'),
        ),
    ]
