# Generated by Django 2.0.1 on 2018-03-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotuto_models', '0003_auto_20180321_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='var',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='var',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='var',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fotuto_models.Device'),
            preserve_default=False,
        ),
    ]
