# Generated by Django 2.0.3 on 2018-04-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotuto_models', '0005_auto_20180403_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('AL', 'Alimentador'), ('AR', 'Airador'), ('RP', 'Repetidora'), ('FE', 'Feeder')], default='FE', max_length=20),
        ),
        migrations.AlterField(
            model_name='var',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotuto_models.Device'),
        ),
        migrations.AlterField(
            model_name='var',
            name='var_type',
            field=models.CharField(choices=[('food', 'Food'), ('voltaje', 'Voltaje'), ('presion', 'Presion'), ('api_alarms', 'Alarms')], default='voltaje', max_length=15),
        ),
        migrations.AddField(
            model_name='varlog',
            name='var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotuto_models.Var'),
        ),
    ]
