# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotuto_models', '0006_auto_20180418_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('FE', 'Feeder')], default='FE', max_length=20),
        ),
    ]
