# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:24
from __future__ import unicode_literals

from django.db import migrations


def create_monitor_and_alarms(apps, schema_monitor):
    ''' Create Monitor and Alarms with information about all the api_alarms in the system '''

    Monitor = apps.get_model('alarms', 'Monitor')
    Alarm = apps.get_model('alarms', 'Alarm')

    monitor = Monitor.objects.create(lookups="Q(slug__startswith='api_alarms') & Q(device__profile__name='Feeder')", duration=0)

    alarm = Alarm.objects.create(name='Shield Incompatible', slug='shield-incompatible', formula='{{ var.value | bit:1 }}',
                         description='Cuando el equipo detecta que algun shield no es compatible con el software o hardware')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Equipo Iniciado', slug='equipo-iniciado', formula='{{ var.value | bit:2 }}',description='')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor Temp. Desconectado', slug='sensor-temp-desconectado', formula='{{ var.value | bit:3 }}',
                         description='')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor 1 Desconectado', slug='sensor-1-desconectado', formula='{{ var.value | bit:4 }}',
                         description='Sin consumo o muy bajo')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Firmware con Errores', slug='firmware-con-errores', formula='{{ var.value | bit:5 }}',
                         description='Cuando el programa que llego para ser actualizado contiene errores')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Luz Desconectada', slug='luz-desconectada', formula='{{ var.value | bit:6 }}',
                         description='')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Alimentacion Deshabilitada', slug='alimentacion-deshabilitada', formula='{{ var.value | bit:7 }}',
                         description='Cuando el equipo decide no alimentar, en otra variable se especifica un codigo indicando la causa')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Aspersor Desconectado', slug='aspersor-desconectado', formula='{{ var.value | bit:8 }}',
                         description='Sin consumo o muy bajo')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Aspersor Obstruido', slug='aspersor-obstruido', formula='{{ var.value | bit:9 }}',
                         description='Alto consumo')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Dosificador Desconectado', slug='dosificador-desconectado', formula='{{ var.value | bit:10 }}',
                         description='Sin consumo o muy bajo')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Tolva vacia', slug='tolva-vacia', formula='{{ var.value | bit:11 }}',
                         description='')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Dosificador Obstruido', slug='dosificador-obstruido', formula='{{ var.value | bit:12 }}',
                         description='Alto consumo')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor 2 Desconectado', slug='sensor-2-desconectado', formula='{{ var.value | bit:13 }}',
                         description='Sin consumo o muy bajo')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Hidrófono Desconectado', slug='hidrofono-desconectado', formula='{{ var.value | bit:14 }}',
                         description='Cuando no se detecta ruido')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Batería Baja', slug='bateria-baja', formula='{{ var.value | bit:15 }}',
                         description='Cuando el voltaje de la batería es inferior a un valor prefijado')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Batería Alta', slug='bateria-alta', formula='{{ var.value | bit:16 }}',
                         description='Cuando el voltaje de la batería es superior a un valor prefijado')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor 1 Bajo', slug='sensor-1-bajo', formula='{{ var.value | bit:17 }}',
                         description='Cuando el valor del sensor 1 es inferior a un valor prefijado')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor 1 Alto', slug='sensor-1-alto', formula='{{ var.value | bit:18 }}',
                         description='Cuando el valor del sensor 1 es superior a un valor prefijado')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor 2 Bajo', slug='sensor-2-bajo', formula='{{ var.value | bit:19 }}',
                         description='Cuando el valor del sensor 2 es inferior a un valor prefijado')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Sensor 2 Alto', slug='sensor-2-alto', formula='{{ var.value | bit:20 }}',
                         description='Cuando del valor del sensor 2 es superior a un valor prefijado')
    alarm.monitor.add(monitor)

    alarm = Alarm.objects.create(name='Alimentación Máxima', slug='alimentacion-maxima', formula='{{ var.value | bit:31 }}',
                         description='Cuando se supera alimentación máxima diaria definida por el usuario')
    alarm.monitor.add(monitor)

def remove_monitor_and_alarms(apps, schema_monitor):
    Monitor = apps.get_model('alarms', 'Monitor')
    Alarm = apps.get_model('alarms', 'Alarm')

    Monitor.objects.all().delete()
    Alarm.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_monitor_and_alarms, remove_monitor_and_alarms),
    ]